### ISSUE TITLE
Error message: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by oakrefactory** [DotNetPlus/ReswPlus#18]
After installing the extension and choosing the menu option 'Generate advanced class', I got the null reference error message.

**Comment by rudyhuyn** [comment]
Hi @oakrefactory, I can repro the issue. Which version of Visual Studio do you use? Which programming language do you use?

Rudy

**Comment by oakrefactory** [comment]
I use VS Community 16.4.2. I use C#.

**Comment by rudyhuyn** [comment]
Problem fixed with ReswPlus 2.1!
