### ISSUE TITLE
Only one resw file supported per folder?

### ISSUE THREAD

**Issue by chrisjshields** [DotNetPlus/ReswPlus#19]
A second resw file duplicates the generated code, rather than seperating them into a second class. Is this a limitation?

**Comment by chrisjshields** [comment]
Sorry - just noticed this was fixed in the source :-) Will you be updating the extension on the Visual Studio marketplace?

**Comment by rudyhuyn** [comment]
The extension is up to date in the VS Marketplace (v2.0). Can you give me more details about your issue?

**Comment by chrisjshields** [comment]
Hi rudyhuyn,

Thanks for getting back to me so quickly. To reproduce this issue in Visual Studio 2019 Version 16.6.0 Preview 2.1, create a new Blank App (Universal Windows) C# project. Add 2 or more resw files to the project in the same folder e.g. the project root. Then open these files and right click on each of them in turn, selecting ReswPlus > Generate only accessors. The tool will not reliably choose the correct class name for the resw file you right clicked on and you therefore get clashes like this:

![image](https://user-images.githubusercontent.com/35778247/78367083-6f9a3c80-75b9-11ea-9c6b-924fcd5dddcd.png)

I can look into this further if you still can't produce this. I'll try a non-preview build of VS if need-be.

**Comment by chrisjshields** [comment]
It seems like once you have run the tool for a single resw file, any further runs will continue to use this resw file, regardless of which resw file you have open in the editor or which one you right click when selecting the tool

**Comment by chrisjshields** [comment]
The Microsoft.VisualStudio.Shell.ServiceProvider needs to recreated every time the custom tool is run, otherwise it is associated with the filename from the previous invocation.

**Comment by rudyhuyn** [comment]
You are right! I will review your PR! Thanks
